# Generated by Django 5.2.1 on 2025-05-31 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_classroom_subject_assignment_classroom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.classroom'),
        ),
    ]
