# Generated by Django 5.2.1 on 2025-05-31 13:52

from django.db import migrations, models
import datetime
from django.utils.timezone import now


def set_marked_at_default(apps, schema_editor):
    Attendance = apps.get_model('core', 'Attendance')
    for attendance in Attendance.objects.all():
        if not attendance.marked_at:
            attendance.marked_at = now()
            attendance.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_profile_classroom'),
    ]

    operations = [
        migrations.RunPython(set_marked_at_default),
    ]
