# Generated by Django 5.2.1 on 2025-05-31 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_attendance_marked_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='exam_type',
            field=models.CharField(choices=[('pa1', 'PA1'), ('half_yearly', 'Half Yearly'), ('pa2', 'PA2'), ('finals', 'Finals'), ('pre_board_1', 'Pre Board 1'), ('pre_board_2', 'Pre Board 2')], default='pa1', max_length=20),
        ),
    ]
